POST http://localhost:8000/new-project
Content-Type: application/json

{
    "project": {
        "name": "test-project2",
        "deadline": "April 25 2017",
        "estimatedCost": 30,
        "notes": ""
    },
    "id":"63d03c5a69e1e5f6962a4819"
}

###

DELETE  http://localhost:8000/delete-project
Content-Type: application/json

{
    "projectName":"test-project2",
    "id":"63d03c5a69e1e5f6962a4819"
}

###
GET http://localhost:8000/users

###

POST http://localhost:8000/get-user
Content-Type: application/json

{
    "username": "davidjustice28",
    "password": "Testpassword"
}

###

POST http://localhost:8000/updateproject 
Content-Type: application/json

{
    "project": {
        "name": "test-project2",
        "deadline": "June 6 2023",
        "estimatedCost": 70,
        "notes": ""
    },
    "id":"63d03c5a69e1e5f6962a4819"
}

###

PUT http://localhost:8000/updatenote
Content-Type: application/json

{
    "note": "",
    "id": "63d03c5a69e1e5f6962a4819",
    "projectName": "test-project2"
}